<?php

/**
 * Implementation of hook_theme.
 */
function media_multiselect_theme() {
  return array(
    'media_multiselect_empty_field' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implementation of hook_requirements
 * Warns the user when they have only enabled plupload, but not multiform.
 */
function media_multiselect_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    if (module_exists('plupload') && !module_exists('multiform')) {
      $requirements[] = array(
        'title' => t('Media Multiselect'),
        'value' => t('Plupload depends on Multiform'),
        'description' => t('Multi uploading using Plupload doesn\'t work as it should without also enabling the Multiform module. So either disable Plupload or enable Multiform.'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  return $requirements;
}

/**
 * Implements hook_field_widget_info().
 */
function media_multiselect_field_widget_info() {
  $widget_info = media_field_widget_info();
  if (module_exists('mediafield'))
    $widget_info['media_generic']['field types'][] = 'media';

  return array(
    'media_multiselect' => array(
      'label' => t('Media multiselect'),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ) + $widget_info['media_generic']
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function media_multiselect_field_widget_settings_form($field, $instance) {
  return media_field_widget_settings_form($field, $instance);
}

/**
 * Implements hook_field_widget_form().
 */
function media_multiselect_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $form['#entity'] = (!empty($element['#entity'])) ? $element['#entity'] : NULL;

  // We cheat and alter the widget-type to the normal media widget.
  $instance['widget']['type'] = 'media_generic';
  $instance['widget']['module'] = 'media';

  if ($field['cardinality'] == 1) {
    return field_default_form(
      $element['#entity_type'],
      $form['#entity'],
      $field,
      $instance,
      $langcode,
      $items,
      $form,
      $form_state
    );
  }
  else {
    $real_cardinality = $field['cardinality'];
    $field['cardinality'] = -1;
  }

  // Then ask the Field API to generate that widget.
  $element += media_field_widget_form($form, $form_state, $field, $instance, $langcode, $items, $delta, $element);

  // If we have a != 1, != unlimited field, we have a fixed amount of values
  // which we can't ajaxify the 'add-more' button of, as it does not have a
  // 'add-more' button. So abort untill we've found a way around this.
  if ($field['cardinality'] != FIELD_CARDINALITY_UNLIMITED) {
    return $element;
  }

  $element[$element['#file_upload_delta']]['#media_options']['global']['multiselect'] = TRUE;
  $element[$element['#file_upload_delta']]['#process'][] = 'media_multiselect_change_add_button';

  // If we no longer have any items, change the theme to avoid an empty table.
  if ($element['#file_upload_delta'] == 0) {
    $element[$element['#file_upload_delta']]['#add_button_title'] = t('Select media');
  }
  elseif ($element['#file_upload_delta'] == $real_cardinality - 1) {
    $element[$element['#file_upload_delta']]['#add_button_access'] = FALSE;
  }
  else {
    $element[$element['#file_upload_delta']]['#add_button_title'] = t('Add media');
  }

  // Add our JS.
  $element['#attached'] = array(
    'js' => array(
      drupal_get_path('module', 'media_multiselect') . '/media_multiselect.js',
    ),
  );

  $element['#after_build'][] = 'media_multiselect_add_js_settings';

  $element['#process'][] = 'media_multiselect_process_widget_form';

  return $element;
}

/**
 * Change the AJAX info for the add-more button.
 */
function media_multiselect_change_add_button($element) {
  $button = $element['browse_button'];

  $button['#ajax']['event'] = 'media_select';
  $button['#ajax']['callback'] = 'media_multiselect_ajax_callback';
  $button['#submit'][0] = 'media_multiselect_ajax_submit';
  $button['#media_multiselect_value_handler'] = 'media_multiselect_add_more_value_handler';

  if (isset($element['#add_button_access']) && $element['#add_button_access'] === FALSE) {
    $button['#access'] = FALSE;
  }
  else {
    $button['#title'] = $element['#add_button_title'];
  }

  // Remove 'browse' class because media module will overwrite click events for
  // the buttons with this class.
  $button['#attributes']['class'] = array_values(array_diff($button['#attributes']['class'], array('browse')));
  $button['#attributes']['class'][] = 'multi-browse';

  $element['browse_button'] = $button;

  return $element;
}

/**
 * #process-callback for the widget-form.
 * Used to rig the #media_multiselect_field_wrapper-array, and to set up all
 * of the value-elements with their own #process-instruction.
 */
function media_multiselect_process_widget_form($element) {
  $element[$element['#file_upload_delta']]['browse_button']['#media_multiselect_field_wrapper'] = $element['#array_parents'];

  for ($i = 0; $i <= $element['#file_upload_delta']; $i++) {
    $element[$i] += element_info('media');
    $element[$i]['#media_multiselect_field_wrapper'] = $element['#array_parents'];
  }

  // Prefix and suffix used for Ajax replacement.
  $element['#prefix'] = '<div id="' . $element['#id'] . '-ajax-wrapper">';
  $element['#suffix'] = '</div>';

  return $element;
}

/**
 * Element-process callback. See @media_multiselect_change_add_button
 */
function media_multiselect_add_js_settings($element) {
  static $processed = array();

  // Add the media-options so the add-more button has the correct options for
  // opening the dialog.
  // We use a static variable to prevent we add the settings more than once
  $id = $element[$element['#file_upload_delta']]['browse_button']['#id'];
  if (empty($processed[$id])) {
    drupal_add_js(array(
      'media' => array(
        'multi_select' => array(
          'elements' => array(
            $id => $element[$element['#file_upload_delta']]['#media_options'],
          ),
        ),
      ),
    ), 'setting');
    $processed[$id] = TRUE;
  }

  return $element;
}

/**
 * Theme callback for empty multiselect media-fields
 */
function theme_media_multiselect_empty_field($vars) {
  $element = $vars['element'];

  $attributes['class'] = array('form-item');
  if (!empty($element['#type'])) {
    $attributes['class'][] = 'form-type-' . strtr($element['#type'], '_', '-');
  }
  if (!empty($element['#name'])) {
    $attributes['class'][] = 'form-item-' . strtr($element['#name'], array(' ' => '-', '_' => '-', '[' => '-', ']' => ''));
  }
  // Add a class for disabled elements to facilitate cross-browser styling.
  if (!empty($element['#attributes']['disabled'])) {
    $attributes['class'][] = 'form-disabled';
  }
  $output = '<div' . drupal_attributes($attributes) . '>' . "\n";
  $output .= theme('form_element_label', $element);
  $output .= '<div class="description">' . $element['#description'] . "</div>\n";
  $output .= '<div class="clearfix">' . drupal_render($element[$element['#file_upload_delta']]['browse_button']) . '</div>';
  $output .= "</div>\n";

  return $output;
}

/**
 * AJAX callback. See @media_multiselect_change_add_button
 *
 * Returns the element in the form identified by the path in the
 * "#media_multiselect_field_wrapper"-property
 * If there are any 'media_multiselect_fid'-values present, it will try
 * to add a 'ajax-new-content'-wrapper around those fields.
 */
function media_multiselect_ajax_callback($form, $form_state) {
  $button = $form_state['triggering_element'];

  // Go one level up in the form, to the widgets container.
  $elements = drupal_array_get_nested_value($form, $button['#media_multiselect_field_wrapper']);

  if (!empty($form_state['input']['media_multiselect_fids'])) {
    // Find the fids that was just added
    $selected_fids = $form_state['input']['media_multiselect_fids'];

    // Run through the elements in the form and add the 'ajax-new-content'
    // wrapper around the new files
    $children = element_children($elements);
    foreach ($children AS $child) {
      $element = &$elements[$child];
      if (!empty($element['#value']['fid']) && in_array($element['#value']['fid'], $selected_fids)) {
        $element['#prefix'] = '<div class="ajax-new-content">';
        $element['#suffix'] = '</div>';
      }
    }
  }

  return $elements;
}

/**
 * AJAX add-more button #submit. See @media_multiselect_change_add_button
 *
 * Finds the current value of the field identified by #media_multiselect_field_wrapper,
 * passes it to the value-handler identified by #media_multiselect_value_handler, and
 * then saves the value back to the field and asks to rebuild the form.
 */
function media_multiselect_ajax_submit($form, &$form_state) {
  $button = $form_state['triggering_element'];
  if (empty($button['#media_multiselect_value_handler'])
   || !is_callable($button['#media_multiselect_value_handler'])) return;

  // Go one level up in the form, to the widgets container.
  $element = drupal_array_get_nested_value($form, $button['#media_multiselect_field_wrapper']);
  $value = drupal_array_get_nested_value($form_state['values'], $button['#media_multiselect_field_wrapper']);

  // Some convenient short-hand variables.
  $field_name = $element['#field_name'];
  $langcode = $element['#language'];
  $parents = $element['#field_parents'];
  $field_state = field_form_get_state($parents, $field_name, $langcode, $form_state);

  // Filter the existing values so only fid > 0 remains.
  $value = array_filter($value, '_media_multiselect_filter_empty_value');
  // Sort according to weight.
  _field_sort_items($field_state['field'], $value);

  // Call the media_multiselect data-handler
  $value = call_user_func($button['#media_multiselect_value_handler'], $form, $form_state, $value);

  // And then re-key the array.
  $value = array_values($value);

  // Update the Field State to the new amount of items
  $field_state['items_count'] = count($value);
  field_form_set_state($parents, $field_name, $langcode, $form_state, $field_state);

  // Update the Form State to make it seem like it received the new files as an input.
  drupal_array_set_nested_value($form_state['input'], $button['#media_multiselect_field_wrapper'], $value);

  $form_state['rebuild'] = TRUE;
}

/**
 * #media_multiselect_value_handler-callback for the 'add more'-button.
 * Checks for any 'media_multiselect_fids'-values and if they are present, they
 * get added to the end of the $value-array.
 */
function media_multiselect_add_more_value_handler($form, $form_state, $value) {
  // Find the highest weight, so we know where to continue from.
  if (!empty($value)) {
    $last_entry = end($value);
    $max_weight = $last_entry['_weight'];
  }
  else {
    $max_weight = -1;
  }

  if (!empty($form_state['input']['media_multiselect_fids'])) {
    // Add the selected fids to the list of values
    foreach ($form_state['input']['media_multiselect_fids'] AS $fid) {
      $value[] = array(
        'fid' => $fid,
        '_weight' => ++$max_weight,
        );
    }
  }
  return $value;
}

/**
 * Helper function to remove empty file values (fid=0)
 */
function _media_multiselect_filter_empty_value($value) {
  return !empty($value['fid']);
}

/**
 * Implements hook_field_validate()
 */
function media_multiselect_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  media_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, $errors);
}
